

/* This is generated code, don't modify */
import EntityTypesIfc from './entity_types_ifc.gen'
import StepEntityInternalReference from '../../step/step_entity_internal_reference'
import StepEntityBase from '../../step/step_entity_base'
import StepModelBase from '../../step/step_model_base'

///**
// * http://www.buildingsmart-tech.org/ifc/ifc4/final/html/link/ifcrepresentationitem.htm */
export abstract class IfcRepresentationItem extends StepEntityBase< EntityTypesIfc > {
  public get type(): EntityTypesIfc {
    return EntityTypesIfc.IFCREPRESENTATIONITEM
  }



  constructor(
    localID: number,
    internalReference: StepEntityInternalReference< EntityTypesIfc >,
    model: StepModelBase< EntityTypesIfc, StepEntityBase< EntityTypesIfc > > ) {
    super( localID, internalReference, model )
  }

  public static readonly query = 
    [ EntityTypesIfc.IFCMAPPEDITEM, EntityTypesIfc.IFCSTYLEDITEM, EntityTypesIfc.IFCANNOTATIONFILLAREA, EntityTypesIfc.IFCBOOLEANRESULT, EntityTypesIfc.IFCBOUNDINGBOX, EntityTypesIfc.IFCCOMPOSITECURVESEGMENT, EntityTypesIfc.IFCDIRECTION, EntityTypesIfc.IFCFACEBASEDSURFACEMODEL, EntityTypesIfc.IFCFILLAREASTYLEHATCHING, EntityTypesIfc.IFCFILLAREASTYLETILES, EntityTypesIfc.IFCGEOMETRICSET, EntityTypesIfc.IFCHALFSPACESOLID, EntityTypesIfc.IFCPLANAREXTENT, EntityTypesIfc.IFCSECTIONEDSPINE, EntityTypesIfc.IFCSHELLBASEDSURFACEMODEL, EntityTypesIfc.IFCTEXTLITERAL, EntityTypesIfc.IFCVECTOR, EntityTypesIfc.IFCBOOLEANCLIPPINGRESULT, EntityTypesIfc.IFCCARTESIANPOINTLIST2D, EntityTypesIfc.IFCCARTESIANPOINTLIST3D, EntityTypesIfc.IFCCARTESIANTRANSFORMATIONOPERATOR2D, EntityTypesIfc.IFCCARTESIANTRANSFORMATIONOPERATOR3D, EntityTypesIfc.IFCCARTESIANTRANSFORMATIONOPERATOR2DNONUNIFORM, EntityTypesIfc.IFCCARTESIANTRANSFORMATIONOPERATOR3DNONUNIFORM, EntityTypesIfc.IFCREPARAMETRISEDCOMPOSITECURVESEGMENT, EntityTypesIfc.IFCBLOCK, EntityTypesIfc.IFCRECTANGULARPYRAMID, EntityTypesIfc.IFCRIGHTCIRCULARCONE, EntityTypesIfc.IFCRIGHTCIRCULARCYLINDER, EntityTypesIfc.IFCSPHERE, EntityTypesIfc.IFCLINE, EntityTypesIfc.IFCOFFSETCURVE2D, EntityTypesIfc.IFCOFFSETCURVE3D, EntityTypesIfc.IFCPCURVE, EntityTypesIfc.IFCSURFACECURVE, EntityTypesIfc.IFCCOMPOSITECURVE, EntityTypesIfc.IFCINDEXEDPOLYCURVE, EntityTypesIfc.IFCPOLYLINE, EntityTypesIfc.IFCTRIMMEDCURVE, EntityTypesIfc.IFCBSPLINECURVEWITHKNOTS, EntityTypesIfc.IFCRATIONALBSPLINECURVEWITHKNOTS, EntityTypesIfc.IFCCOMPOSITECURVEONSURFACE, EntityTypesIfc.IFCBOUNDARYCURVE, EntityTypesIfc.IFCOUTERBOUNDARYCURVE, EntityTypesIfc.IFCCIRCLE, EntityTypesIfc.IFCELLIPSE, EntityTypesIfc.IFCINTERSECTIONCURVE, EntityTypesIfc.IFCSEAMCURVE, EntityTypesIfc.IFCGEOMETRICCURVESET, EntityTypesIfc.IFCBOXEDHALFSPACE, EntityTypesIfc.IFCPOLYGONALBOUNDEDHALFSPACE, EntityTypesIfc.IFCLIGHTSOURCEAMBIENT, EntityTypesIfc.IFCLIGHTSOURCEDIRECTIONAL, EntityTypesIfc.IFCLIGHTSOURCEGONIOMETRIC, EntityTypesIfc.IFCLIGHTSOURCEPOSITIONAL, EntityTypesIfc.IFCLIGHTSOURCESPOT, EntityTypesIfc.IFCAXIS1PLACEMENT, EntityTypesIfc.IFCAXIS2PLACEMENT2D, EntityTypesIfc.IFCAXIS2PLACEMENT3D, EntityTypesIfc.IFCPLANARBOX, EntityTypesIfc.IFCCARTESIANPOINT, EntityTypesIfc.IFCPOINTONCURVE, EntityTypesIfc.IFCPOINTONSURFACE, EntityTypesIfc.IFCCSGSOLID, EntityTypesIfc.IFCSWEPTDISKSOLID, EntityTypesIfc.IFCADVANCEDBREP, EntityTypesIfc.IFCFACETEDBREP, EntityTypesIfc.IFCADVANCEDBREPWITHVOIDS, EntityTypesIfc.IFCFACETEDBREPWITHVOIDS, EntityTypesIfc.IFCEXTRUDEDAREASOLID, EntityTypesIfc.IFCFIXEDREFERENCESWEPTAREASOLID, EntityTypesIfc.IFCREVOLVEDAREASOLID, EntityTypesIfc.IFCSURFACECURVESWEPTAREASOLID, EntityTypesIfc.IFCEXTRUDEDAREASOLIDTAPERED, EntityTypesIfc.IFCREVOLVEDAREASOLIDTAPERED, EntityTypesIfc.IFCSWEPTDISKSOLIDPOLYGONAL, EntityTypesIfc.IFCCURVEBOUNDEDPLANE, EntityTypesIfc.IFCCURVEBOUNDEDSURFACE, EntityTypesIfc.IFCRECTANGULARTRIMMEDSURFACE, EntityTypesIfc.IFCBSPLINESURFACEWITHKNOTS, EntityTypesIfc.IFCRATIONALBSPLINESURFACEWITHKNOTS, EntityTypesIfc.IFCCYLINDRICALSURFACE, EntityTypesIfc.IFCPLANE, EntityTypesIfc.IFCSPHERICALSURFACE, EntityTypesIfc.IFCTOROIDALSURFACE, EntityTypesIfc.IFCSURFACEOFLINEAREXTRUSION, EntityTypesIfc.IFCSURFACEOFREVOLUTION, EntityTypesIfc.IFCINDEXEDPOLYGONALFACE, EntityTypesIfc.IFCINDEXEDPOLYGONALFACEWITHVOIDS, EntityTypesIfc.IFCPOLYGONALFACESET, EntityTypesIfc.IFCTRIANGULATEDFACESET, EntityTypesIfc.IFCTEXTLITERALWITHEXTENT, EntityTypesIfc.IFCCONNECTEDFACESET, EntityTypesIfc.IFCEDGE, EntityTypesIfc.IFCFACE, EntityTypesIfc.IFCFACEBOUND, EntityTypesIfc.IFCLOOP, EntityTypesIfc.IFCPATH, EntityTypesIfc.IFCVERTEX, EntityTypesIfc.IFCCLOSEDSHELL, EntityTypesIfc.IFCOPENSHELL, EntityTypesIfc.IFCEDGECURVE, EntityTypesIfc.IFCORIENTEDEDGE, EntityTypesIfc.IFCSUBEDGE, EntityTypesIfc.IFCFACESURFACE, EntityTypesIfc.IFCADVANCEDFACE, EntityTypesIfc.IFCFACEOUTERBOUND, EntityTypesIfc.IFCEDGELOOP, EntityTypesIfc.IFCPOLYLOOP, EntityTypesIfc.IFCVERTEXLOOP, EntityTypesIfc.IFCVERTEXPOINT ]

  public static readonly expectedType: EntityTypesIfc =
    EntityTypesIfc.IFCREPRESENTATIONITEM
}
