#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# TODO(pablo): weird issue
# https://stackoverflow.com/questions/21058363/git-failing-to-find-the-index-when-in-submodule-index-file-open-failed-not-a
# Temporary workaround is to not cd into submodules in precommit.. just lint and update version.

yarn precommit
